spring:
  thymeleaf:
    enabled: true
    encoding: utf-8
    check-template-location: true
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:6033/mydb
    username: root
    password: 123456
#亲测无效
#  session:
#    timeout: 60s

#超时设置
server:
  servlet:
    session:
      timeout: 15m
      cookie:
      #js脚本不能访问cookie
        http-only: true
        secure: false



